steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - get_tft_data
  - --region=us-central1
  - --gen2
  - --source=.
  - --entry-point=read_event
  - --set-secrets=RIOT_API_KEY=RIOT_API_KEY:latest
  - --trigger-topic=twice-per-day
  - --runtime=python311